import Head from 'next/head'
import {Inter} from 'next/font/google'
import Header from "@/components/Header";

// const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Justin P. Dickerson | SWE</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main>
                <section>
                    <h2>Professional Site</h2>
                    <h3>Introduction</h3>
                    <p>
                        Greetings! My name is Justin a freelance software
                        engineer within the mobile & web development space. Additionally, a student at Oregon State
                        University for their post-baccalaureate curriculum in Computer
                        Science via Ecampus. Interested in hiring or booking me? Download my resume via a computer and
                        then send me an email along with a description of the job or project requirements.
                        I will gladly review and reach out if the project is potential fit. Have a wonderful day!
                    </p>
                    <h3>About</h3>
                    <p>
                        Welcome to the redesign of my professional site. The website utilizes Next.js within the MERN
                        architecture. With Next.js, the site is able to take full advantage of automatic routing.
                    </p>
                </section>
            </main>
            <footer>
                <p>&copy; 2023 Justin Dickerson. All rights reserved.</p>
            </footer>
        </>
    )
}
